# Generated by Django 5.2.1 on 2025-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
